# CLI tools
brew "neovim"
brew "awscli"
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "duti" # sets the default app per extension (macos/scripts/register-file-handlers.sh)
brew "fd"
brew "fzf"
brew "gh"
brew "ghq"
brew "glow"
brew "go" # also builds claude/csr in setup.sh
brew "git"
brew "git-delta"
brew "hunk"
brew "hyperfine"
brew "jq"
brew "lazygit"
brew "libgit2"
brew "mise"
brew "mkcert"
brew "mysql-client"
brew "mysql@8.4"
brew "ripgrep"
brew "rtk"
brew "sheldon"
brew "starship"
brew "tig"
brew "tmux"
brew "uv"
brew "zoxide"

# Casks
cask "aws-vault-binary"
cask "font-monaspace-nf"
cask "ngrok"
