package main

import (
	"fmt"
	"strings"
)

const cheatsheetPath = "docs/cheatsheet.md"

// sectionTitles give each category a heading that says where you are when you
// use it.
var sectionTitles = map[string]string{
	"shell":   "Shell (zsh)",
	"tmux":    "tmux",
	"nvim":    "Neovim",
	"gh":      "GitHub CLI",
	"gh-dash": "gh-dash (PR dashboard)",
	"claude":  "Claude Code skills",
	"macOS":   "macOS (Karabiner)",
}

// Render builds docs/cheatsheet.md. It is generated, so it carries a banner
// saying so: editing it by hand is wasted work, the annotations are the source.
func Render(entries []Entry) string {
	var b strings.Builder

	b.WriteString("# Cheatsheet\n\n")
	b.WriteString("<!-- Generated by tools/cheatsheet (`keys --generate`). Do not edit by hand. -->\n")
	b.WriteString("<!-- Descriptions come from `#:` annotations next to each definition. -->\n\n")
	b.WriteString("Everything this repo lets you type. Browse it in a terminal with `keys`,\n")
	b.WriteString("or `keys <query>` to filter.\n")

	current := ""
	for _, e := range entries {
		if e.Category != current {
			current = e.Category
			title := sectionTitles[current]
			if title == "" {
				title = current
			}
			fmt.Fprintf(&b, "\n## %s\n\n| Press / type | Does | Defined in |\n|---|---|---|\n", title)
		}
		fmt.Fprintf(&b, "| `%s` | %s | `%s` |\n",
			escapePipes(e.Key), escapePipes(e.Desc), e.Source())
	}

	return b.String()
}

func escapePipes(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}

// pickerLines are what fzf shows: category, key, description, source.
func pickerLines(entries []Entry) []string {
	width := 0
	for _, e := range entries {
		if n := len(e.Key); n > width {
			width = n
		}
	}

	lines := make([]string, 0, len(entries))
	for _, e := range entries {
		lines = append(lines, fmt.Sprintf("%-9s %-*s  %s  (%s)",
			e.Category, width, e.Key, e.Desc, e.Source()))
	}
	return lines
}
